project_id = "ljofnwcvpzqlhagejgbk"

[functions.calcular-frete]
verify_jwt = false

[functions.verificar-alertas]
verify_jwt = false

[functions.gerar-relatorio-pdf]
verify_jwt = false

[functions.enviar-whatsapp]
verify_jwt = false

[functions.notificar-visualizacao-maleta]
verify_jwt = false

[functions.notificar-novo-pedido-revendedora]
verify_jwt = false

[functions.stripe-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.verificar-assinaturas]
verify_jwt = false

[functions.verificar-senha-portal]
verify_jwt = false

[functions.agente-ia]
verify_jwt = false

[functions.webhook-whatsapp]
verify_jwt = false

[functions.evolution-instance]
verify_jwt = false

[functions.gerar-codigo-acesso]
verify_jwt = false
