
-- Add new columns to ecommerce_config for enhanced customization
ALTER TABLE public.ecommerce_config
  ADD COLUMN IF NOT EXISTS banner_url text,
  ADD COLUMN IF NOT EXISTS banner_link text,
  ADD COLUMN IF NOT EXISTS banner_posicao text DEFAULT 'topo',
  ADD COLUMN IF NOT EXISTS fonte_titulos text DEFAULT 'Cormorant Garamond',
  ADD COLUMN IF NOT EXISTS fonte_corpo text DEFAULT 'Inter',
  ADD COLUMN IF NOT EXISTS layout_produtos text DEFAULT 'grid',
  ADD COLUMN IF NOT EXISTS colunas_desktop integer DEFAULT 4,
  ADD COLUMN IF NOT EXISTS colunas_mobile integer DEFAULT 2,
  ADD COLUMN IF NOT EXISTS mostrar_busca boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS mostrar_categorias boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS mostrar_filtros boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS mostrar_ordenacao boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS mostrar_whatsapp_float boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS whatsapp_posicao text DEFAULT 'direita',
  ADD COLUMN IF NOT EXISTS selos_confianca text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS texto_rodape text,
  ADD COLUMN IF NOT EXISTS google_analytics_id text,
  ADD COLUMN IF NOT EXISTS facebook_pixel_id text,
  ADD COLUMN IF NOT EXISTS css_personalizado text,
  ADD COLUMN IF NOT EXISTS hero_titulo text,
  ADD COLUMN IF NOT EXISTS hero_subtitulo text,
  ADD COLUMN IF NOT EXISTS hero_cta_texto text DEFAULT 'Ver Coleção',
  ADD COLUMN IF NOT EXISTS hero_cta_link text,
  ADD COLUMN IF NOT EXISTS hero_imagem_url text,
  ADD COLUMN IF NOT EXISTS hero_overlay_opacity numeric DEFAULT 0.4,
  ADD COLUMN IF NOT EXISTS parcelamento_max integer DEFAULT 12,
  ADD COLUMN IF NOT EXISTS mostrar_parcelamento boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS tempo_estimado_entrega text,
  ADD COLUMN IF NOT EXISTS badges_produto text[] DEFAULT '{}'::text[];
