// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://acmgwqjkvnuncplnypcm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjbWd3cWprdm51bmNwbG55cGNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg4MzUyODIsImV4cCI6MjA4NDQxMTI4Mn0.gpcS4LM3im9hvpoWpW5MNlZNIQ5gw2sq6EUO4G-ZufM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});